### ISSUE TITLE
Practica Architec

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/practica-architect-JazminloRI#1]
[Practica Architect.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-JazminloRI/files/7151237/Practica.Architect.pdf)
[Diagrama de clase.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-JazminloRI/files/7151276/Diagrama.de.clase.pdf)

**Comment by scristianj** [comment]
Calificación: 20%

**Comment by scristianj** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
